// lib/complexity/schreier-sims.ts
//
// Q-044 audit 4 — a provably-correct polynomial-time fast path for the
// holonomy-group ORDER computation in the H¹-rank primitive.
//
// See:
//   RESEARCH_PROGRAMME/audits/q044-h1rank-schreier-sims-2026-07-05.md
//   scripts/plexus-topology-probe.ts  (computeH1RankBasis — the drop-in target)
//   RESEARCH_PROGRAMME/02_THEOREMS_AND_PROOFS/T011-possibilistic-cohomology-iso-monodromy.md
//
// THE PROBLEM (audit §2). `computeH1RankBasis` computes the H¹ rank as
// log₂|G|, where G = ⟨σ_e⟩ is the holonomy group generated by the fundamental-
// cycle permutations. It obtains |G| by a NAIVE ORBIT CLOSURE — repeatedly
// composing every element by every generator until no new element appears —
// which materialises all |G| elements, so it is Θ(|G|²·β1) and |G| can be
// exponential in β1 (the number of non-tree edges). Its `guard++ < 1000` caps the
// number of BFS ROUNDS (Cayley word-length layers), NOT the element count, so for
// typical low-diameter groups it returns the CORRECT order but at Θ(|G|²) cost
// (and OOMs/hangs on exponential |G|); a silently-truncated wrong order arises
// only in the rare Cayley-diameter > 1000 regime (cross-check D1, 2026-07-06).
//
// THE FIX. The order of a permutation group given its generators is computable
// in POLYNOMIAL time in the degree d (number of permuted points) and generator
// count, WITHOUT enumerating G, by Schreier–Sims: build a base and strong
// generating set (BSGS); then |G| = ∏ (basic orbit lengths) along the base.
// This module implements the incremental deterministic Schreier–Sims with
// SIFTING (`buildBSGS`): Schreier generators are stripped through the partial
// stabiliser chain and only non-identity residues are kept as strong generators,
// which bounds the strong-generator count to O(d²) and secures the worst-case
// POLYNOMIAL bound in the routine itself (closing the earlier dedup-only gap,
// cross-check D2, 2026-07-06). Plus `sift`/`contains` (membership) and the cheap
// generator-level elementary-abelian-2 test the rank exactness depends on.
//
// PURE. No I/O, no prisma, no clock. Permutations are total bijections on a
// finite string ground set (Map<point, point>); a partial holonomy is completed
// to a permutation by fixing unmapped points (documented in `toPermutation`).

export type Perm = Map<string, string>;

// ---------------------------------------------------------------------------
// Permutation algebra over a fixed ground set
// ---------------------------------------------------------------------------

const apply = (g: Perm, x: string): string => g.get(x) ?? x;

/** (g ∘ f)(x) = g(f(x)), total over `pts`. */
function compose(g: Perm, f: Perm, pts: readonly string[]): Perm {
  const out: Perm = new Map();
  for (const x of pts) out.set(x, apply(g, apply(f, x)));
  return out;
}

function inverse(g: Perm, pts: readonly string[]): Perm {
  const out: Perm = new Map();
  for (const x of pts) out.set(apply(g, x), x);
  return out;
}

function identity(pts: readonly string[]): Perm {
  return new Map(pts.map((p) => [p, p] as const));
}

function isIdentity(g: Perm, pts: readonly string[]): boolean {
  for (const x of pts) if (apply(g, x) !== x) return false;
  return true;
}

/** Canonical key of a permutation over `pts` (for dedup / membership). */
function key(g: Perm, pts: readonly string[]): string {
  return pts.map((x) => apply(g, x)).join(",");
}

/**
 * Complete a (possibly partial) holonomy map to a total permutation over `pts`
 * by fixing unmapped points. Throws if the completion is not a bijection — a
 * malformed holonomy (a monodromy permutation on a fibre must be a bijection).
 */
export function toPermutation(map: ReadonlyMap<string, string>, pts: readonly string[]): Perm {
  const g: Perm = new Map(pts.map((p) => [p, map.get(p) ?? p] as const));
  const image = new Set(g.values());
  if (image.size !== pts.length) {
    throw new Error("toPermutation: holonomy map is not a bijection over the ground set");
  }
  return g;
}

/** The union of all points a set of (partial) maps mentions — the ground set. */
export function groundSet(maps: ReadonlyArray<ReadonlyMap<string, string>>): string[] {
  const s = new Set<string>();
  for (const m of maps) for (const [k, v] of m) { s.add(k); s.add(v); }
  return [...s].sort();
}

// ---------------------------------------------------------------------------
// Schreier–Sims — exact group order in polynomial time (BSGS + sifting)
// ---------------------------------------------------------------------------
//
// This is the incremental deterministic Schreier–Sims: it builds a base
// `B = [b₁,…,b_k]` and a strong generating set `S` (a BSGS) by repeatedly
// forming Schreier generators, **sifting** each through the partial stabiliser
// chain, and keeping only the non-identity residues as new strong generators
// (extending the base when a residue fixes the whole base). Sifting is what
// bounds the strong-generator count to `O(d²)` — closing the cross-check D2 gap:
// the routine now realises the worst-case polynomial bound itself, not merely by
// citation. `|G| = ∏ |basic orbit_i|`, computed without enumerating `G`.

/** Basic orbit + Schreier transversal of `root` under `gens`: `trans[x](root) = x`. */
function orbitTransversal(root: string, gens: readonly Perm[], pts: readonly string[]): Map<string, Perm> {
  const trans = new Map<string, Perm>([[root, identity(pts)]]);
  const queue: string[] = [root];
  while (queue.length) {
    const x = queue.shift()!;
    const ux = trans.get(x)!;
    for (const g of gens) {
      const y = apply(g, x);
      if (!trans.has(y)) {
        trans.set(y, compose(g, ux, pts)); // sends root ↦ y
        queue.push(y);
      }
    }
  }
  return trans;
}

export interface BSGS {
  /** The base `[b₁,…,b_k]`. */
  base: string[];
  /** Per-level basic orbit + transversal (`orbits[i]` for `base[i]`, under strong gens fixing `base[0..i-1]`). */
  orbits: Array<Map<string, Perm>>;
  /** The strong generating set. */
  strongGens: Perm[];
  /** `|G| = ∏ |orbits[i]|`, exact. */
  order: bigint;
  /** The ground set the permutations act on. */
  pts: readonly string[];
}

/**
 * Sift (strip) `g` through the BSGS: return the residue and the level at which
 * it drops out. `g ∈ ⟨S⟩` iff the residue is the identity and `level = base.length`.
 */
export function sift(g: Perm, bsgs: Pick<BSGS, "base" | "orbits" | "pts">): { residue: Perm; level: number } {
  const { base, orbits, pts } = bsgs;
  let h = g;
  for (let i = 0; i < base.length; i++) {
    const x = apply(h, base[i]);
    const u = orbits[i].get(x);
    if (u === undefined) return { residue: h, level: i }; // drops out at level i
    h = compose(inverse(u, pts), h, pts); // now h fixes base[i]
  }
  return { residue: h, level: base.length };
}

/** Membership test: is `g ∈ ⟨S⟩`? (`g` sifts to the identity through the whole chain.) */
export function contains(g: Perm, bsgs: BSGS): boolean {
  const total = new Map(bsgs.pts.map((p) => [p, apply(g, p)] as const));
  const { residue, level } = sift(total, bsgs);
  return level === bsgs.base.length && isIdentity(residue, bsgs.pts);
}

/**
 * Build a base and strong generating set for `⟨generators⟩` on `pts` by
 * incremental Schreier–Sims with sifting. Deterministic, exact, and
 * polynomial in the degree and generator count.
 */
export function buildBSGS(generators: readonly Perm[], pts: readonly string[]): BSGS {
  const base: string[] = [];
  const S: Perm[] = [];

  // Seed: normalise generators to total perms, drop identities, and ensure every
  // generator moves at least one base point.
  for (const raw of generators) {
    const g = new Map(pts.map((p) => [p, apply(raw, p)] as const));
    if (isIdentity(g, pts)) continue;
    if (base.every((b) => apply(g, b) === b)) {
      const p = pts.find((q) => apply(g, q) !== q)!;
      base.push(p);
    }
    S.push(g);
  }

  const gensAtLevel = (i: number): Perm[] =>
    S.filter((s) => base.slice(0, i).every((b) => apply(s, b) === b));
  const orbits: Array<Map<string, Perm>> = [];
  const rebuild = (i: number) => { orbits[i] = orbitTransversal(base[i], gensAtLevel(i), pts); };
  for (let i = 0; i < base.length; i++) rebuild(i);

  // Test/repair from the deepest level up. Each repair strictly grows the chain
  // (a new base point, or a residue that enlarges some basic orbit), and the
  // chain is bounded by |G|, so the loop terminates. The guard turns a bug into
  // an error rather than a hang.
  let i = base.length - 1;
  let guard = 0;
  const guardMax = 100_000 + 100 * pts.length * pts.length;
  while (i >= 0) {
    if (guard++ > guardMax) throw new Error("buildBSGS: repair loop exceeded guard (likely a bug)");
    const gensI = gensAtLevel(i);
    let repaired = false;
    outer: for (const [x, ux] of orbits[i]) {
      for (const s of gensI) {
        const sx = apply(s, x);
        const rep = orbits[i].get(sx)!; // sx ∈ orbit (closed under gensI)
        const schreier = compose(inverse(rep, pts), compose(s, ux, pts), pts); // fixes base[i]
        if (isIdentity(schreier, pts)) continue;
        const { residue, level } = sift(schreier, { base, orbits, pts });
        if (!isIdentity(residue, pts)) {
          if (level === base.length) {
            base.push(pts.find((q) => apply(residue, q) !== q)!); // residue fixes whole base ⇒ extend
            orbits.push(new Map());
          }
          S.push(residue);
          for (let j = i + 1; j < base.length; j++) rebuild(j);
          i = level; // re-verify from the level the residue joined
          repaired = true;
          break outer;
        }
      }
    }
    if (!repaired) i--;
  }

  let order = 1n;
  for (let k = 0; k < base.length; k++) order *= BigInt(orbits[k].size);
  return { base, orbits, strongGens: S, order, pts };
}

/**
 * `|⟨generators⟩|` as a permutation group on `pts`, exact, via Schreier–Sims
 * (BSGS + sifting; polynomial in degree and generator count, no enumeration).
 * Returns a bigint (orders can exceed 2^53 for large degree).
 */
export function groupOrder(generators: readonly Perm[], pts: readonly string[]): bigint {
  return buildBSGS(generators, pts).order;
}

// ---------------------------------------------------------------------------
// Elementary-abelian-2 test (the rank-exactness condition), on generators only
// ---------------------------------------------------------------------------

/**
 * Is ⟨generators⟩ an elementary abelian 2-group (every element an involution)?
 * Checkable on the O(β1) generators alone — no enumeration — because a group
 * generated by involutions has exponent ≤ 2 iff the generators pairwise commute:
 *   (i) each generator is an involution (g² = id), and
 *   (ii) generators pairwise commute (g·h = h·g).
 * Then |G| = 2^k and rank = log₂|G| is EXACT (else it is a lower bound).
 */
export function isElementaryAbelian2(generators: readonly Perm[], pts: readonly string[]): boolean {
  const gens = generators
    .map((g) => new Map(pts.map((p) => [p, apply(g, p)] as const)))
    .filter((g) => !isIdentity(g, pts));
  for (const g of gens) {
    if (!isIdentity(compose(g, g, pts), pts)) return false; // (i) involution
  }
  for (let i = 0; i < gens.length; i++) {
    for (let j = i + 1; j < gens.length; j++) {
      const gh = compose(gens[i], gens[j], pts);
      const hg = compose(gens[j], gens[i], pts);
      if (key(gh, pts) !== key(hg, pts)) return false; // (ii) commute
    }
  }
  return true;
}

// ---------------------------------------------------------------------------
// The H¹-rank read (drop-in replacement for computeH1RankBasis's group step)
// ---------------------------------------------------------------------------

export interface HolonomyGroupResult {
  /** |G|, exact (never truncated). */
  groupOrder: bigint;
  /** log₂|G|, exact when the group is elementary abelian 2, else a lower bound. */
  rank: number;
  elementaryAbelian2: boolean;
}

/**
 * Compute (|G|, rank, e.a.2?) from the fundamental-cycle holonomies, replacing
 * the naive `while (changed && guard < 1000)` closure in `computeH1RankBasis`.
 * Partial holonomies are completed to permutations by `toPermutation`.
 */
export function holonomyGroupRank(
  holonomies: ReadonlyArray<ReadonlyMap<string, string>>
): HolonomyGroupResult {
  const pts = groundSet(holonomies);
  if (pts.length === 0) return { groupOrder: 1n, rank: 0, elementaryAbelian2: true };
  const gens = holonomies.map((h) => toPermutation(h, pts));
  const order = groupOrder(gens, pts);
  const ea2 = isElementaryAbelian2(gens, pts);
  const rank = order > 0n ? Math.floor(Math.log2(Number(order))) : 0;
  return { groupOrder: order, rank, elementaryAbelian2: ea2 };
}
